config/routes.rb
Rails.application.routes.draw do
  resources :lists
  get 'home/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#home"
  resources :valid_followers 
  
  resources :channels do
  	resources :valid_followers
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
	has_many :valid_followers




			  def self.to_csv(options = {})
			  CSV.generate(options) do |csv|
			    csv << column_names
			    all.each do |follower|
			      csv << follower.attributes.values
			    end
		  	end
		  end


	
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/valid_follower.rb
class ValidFollower < ApplicationRecord
  belongs_to :channel
  require 'csv'

		  def self.to_csv(options = {})
			  CSV.generate(options) do |csv|
			    csv << column_names
			    all.each do |follower|
			      csv << follower.attributes.values
			    end
		  	end
		  end


end
	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


# Créer une channel avec New 
# -> URL 

# @channel.url = "URL"
# = perform @channel.url
#


# Lancer le scrapper 
# Ajouter les infos du scrapper a la nouvelle channel 
# Créer des followers et ajouter a la chaine
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

	def new
		@channel = Channel.new
	end

	def create 
		@channel = Channel.new(channel_params)
		@channel = Scrapper.new.perform(@channel.url)
			
		redirect_to root_path, :alert => 'Channel Saved, you can check the new followers'
			
	end

	def index
		@channels = Channel.all
	end

	def show 
		@channel = Channel.find(params[:id])
		respond_to do |format|
      		format.html
     		format.csv { send_data @channels.to_csv, filename: "chan-followers-#{Date.today}.csv" }
     	end
	end

	private 

	def channel_params
      params.require(:channel).permit(:name, :url, :follower_count)
    end

    def channel_url
    	params.require(:channel).permit(:url)
    end

end

	

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home

		
	@channel = Channel.new(channel_params)
	return new_channel_path


	@allusers = Channel.all.each do |channel|
		@allusers += channel.follower_count 
	end

		

  	if @channel.save
  		times_scrolling = (@channel.follower_count.to_i / 22)
  		@estimate_time = Time.at(2*times_scrolling * 1.2).utc.strftime("%H:%M:%S") + (@channel.follower_count * 1.2)
  	end

  end


  	private 

	def channel_params
      params.permit(:name, :url, :follower_count)
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_path, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:url, :note)
    end
end

app/controllers/valid_followers_controller.rb
class ValidFollowersController < ApplicationController








	def show
		@follower = ValidFollower.find(params[:id])
	end

	def index
		@followers = ValidFollower.all

		    respond_to do |format|
      		format.html
     		format.csv { send_data @followers.to_csv, filename: "followers-#{Date.today}.csv" }
    end
	end


	private 

	def valid_follower_params
      params.require(:follower).permit(:username, :handle, :follower_count, :channel_id, :email)
    end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/valid_followers_helper.rb
module ValidFollowersHelper
end

app/views/channels/_form.html.erb
<%= simple_form_for(@channel) do |f| %>

<%= f.input :url, placeholder: "Entrez l'URL de la page souncloud a Scrapper", label: false %>
<%= f.button :submit, "Scrape Soundcloud Channel",	class: "btn btn-treehouse new" %>


<% end %>

app/views/channels/index.html.erb
<h1>Channels</h1>

<div class="channels-header">
<%= link_to "Back", root_path, class: "btn btn-treehouse4" %>
<%= link_to 'Download CSV', valid_followers_path(@followers, format: :csv), class: "btn btn-treehouse2" %>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Channel Name</th>
      <th scope="col">URL</th>
      <th scope="col">Follower</th>
      <th scope="col">With Emails</th>
    </tr>
  </thead>
  <tbody>
  	<% @channels.each do |channel| %>
    <tr>
      <th scope="row"><%= channel.id %></th>
      <td><%= channel.name %></td>
      <td><%= channel.url %></td>
      <td><%= channel.follower_count %></td>
      <td><%= channel.valid_followers.count %></td>
      <td><%= link_to "Details", channel_path(channel) %> </td>
      <td><%= link_to "Mailer" %></td>
    </tr>
	<% end %>

  </tbody>
</table>

app/views/channels/new.html.erb
<h1>New Scrapping</h1>

<%= render "form" %>

app/views/channels/show.html.erb
<ul style="list-style: none;">
<li><h1><%= @channel.name %> </h1></li>
<li><%= @channel.follower_count%> Followers</li>
<li><%= @channel.url%></li>
<li><%= @channel.valid_followers.count%> followers valides <%#= link_to "Afficher", channel_valid_followers_path(@channel) %></li>
</ul>


<table class="table" id="pagefollowerlists">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Username</th>
      <th scope="col">Handle</th>
      <th scope="col">Followers</th>
      <th scope="col">Titres publiés</th>
      <th scope="col">Mails</th>
    </tr>
  </thead>
  <tbody>
<% @channel.valid_followers.each do |follower| %>
    <tr>
      <th scope="row"><%= follower.id %></th>
      <td><%= follower.username %></td>
      <td><%= follower.handle %></td>
      <td><%= follower.follower_count %></td>
      <td> </td>
      <td><%= follower.email.to_s %></td>


      </td>
      <td><%=  %></td>
      <td><%=  %></td>
    </tr>
	<% end %>

  </tbody>
</table>

app/views/home/_form.html.erb
<%= simple_form_for(@channel	) do |f| %>

<%= f.input :url, placeholder: "Entrez l'URL de la page souncloud a Scrapper" %>
<%= f.button :submit %>



<% end %>

app/views/home/home.html.erb
<p></p>

<div class="container">

	<div class="header">
		<div class="titre">
			<h1>Soundcloud Mail Scrapper Robot</h1>
		</div>
		<div class="infos">
			<div class="infos-fonctionnalités">
				<p>Trouver les emails dans les descriptions de chaque followers d'une page soundcloud <p>
				<p>Il cherche les adresses mail dans environs 5'000 description de followers en une heure en 4g  </p>



			</div>
			<div class="infos-stats">
				<h4>Compte rendu du robot</h3>
				<ul style="list-style: none;">
					<li><%= Channel.all.count %> chaines soundcloud scrapés, <%= link_to "Voir la liste", channels_path %></li>
					<li><%= ValidFollower.all.count %> emails trouvés </li>
					<li>Total des utilisateurs scrapés: <%= @allusers %> </li>
				</ul>
			</div>
		</div>
	</div>


	<div class="NewSession">
		<div class="newsession-header">

		</div>
		<div class="newsession-box">
	<%= render 'channels/form', :layout => true %>
 
			<%= @estimate_time %>

		</div>
		<div class="newsession-controls">
			<%= link_to "Followers List", valid_followers_path, class: "btn btn-treehouse2" %>
			<%= link_to "Channels List", channels_path, class: "btn btn-treehouse2" %>
			<%= link_to "Channels to Scrap List", lists_path, class: "btn btn-treehouse5" %>
<%= link_to 'Download CSV', valid_followers_path(@followers, format: :csv), class: "btn btn-treehouse3" %>

		</div>
	</div>

	<div class="downpage">
		<h5 style="margin-top: 32px;">Pour l'instant, vous ne pouvez pas savoir ou le robot en est dans la session de scrapping, veuillez patienter environs 1 heure pour 5000 followers et recharger la page</h5>
	</div>
<div class="container">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PromoAgency</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


  

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :url %>
    <%= f.input :note %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste</h1>
<h3>Ici ajouter des listes de page à Scrapper</h2>
  <%= link_to "Back", root_path, class: "btn btn-treehouse4" %>


<table class="table">
  <thead>
    <tr>
      <th>Url</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.url %></td>
        <td><%= list.note %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @list.url %>
</p>

<p>
  <strong>Note:</strong>
  <%= @list.note %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/valid_followers/index.html.erb
<br>
<div style="margin: 30px;">
<h2> <%= @followers.count %> emails </h2>
<h5> From <%= Channel.all.count %> channels</h5>
<div class="list-followers-controls">
<%= link_to "Back", root_path, class: "btn btn-treehouse4" %>
<%= link_to 'Download CSV', valid_followers_path(@followers, format: :csv), class: "btn btn-treehouse2" %>


</div>
<br>
<table class="table" id="pagefollowerlists">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Username</th>
      <th scope="col">Handle</th>
      <th scope="col">Followers</th>
      <th scope="col">From</th>
      <th scope="col">Mails</th>
      <th scope="col">Titres publiés</th>

    </tr>
  </thead>
  <tbody>
<% @followers.each do |follower| %>
    <tr>
      <th scope="row"><%= follower.id %></th>
      <td><%= follower.username %></td>
      <td><%= follower.handle %></td>
      <td><%= follower.follower_count %></td>
      <td> <%= Channel.find(follower.channel.id).name %></td>
      <td><%= follower.email.to_s %></td>


      </td>
      <td><%=  %></td>
      <td><%=  %></td>
    </tr>
	<% end %>

  </tbody>
</table>

app/views/valid_followers/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Release Date</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
    <% @followers.each do |f| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= f.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= f.handle %></Data></Cell>
        <Cell><Data ss:Type="String"><%= f.follower_count %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= f.email %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>